.TH touchpad-edge-detector 1 "May 1, 2014" libevdev-tools
.SH NAME
touchpad-edge-detector \- touchpad edge detector
.SH SYNOPSIS
.B touchpad\-edge\-detector
<\fIevdev device\fP>
.SH DESCRIPTION
.B touchpad-edge-detector
reads touchpad events and calculates the minimum and maximum values
for the \fIx\fP and \fIy\fP coordinates.
.PP
.SH OPTIONS
.B touchpad-edge-detector
accepts no options.
.SH AUTHORS
\fBtouchpad-edge-detector\fP was written by Peter Hutterer and
Emmanuele Bassi for Red Hat, Inc.
This manual page was adapted from the program usage information by
Stephen Kitt <skitt@debian.org>, for the Debian GNU/Linux system (but
may be used by others). It was last modified for \fBlibevdev\fP version
1.2.
